use axum::{
    extract::{Path, State},
    http::StatusCode,
    response::Json,
    routing::get,
    Router,
};
use chrono::NaiveDateTime;
use diesel::pg::Pg;
use diesel::pg::PgConnection;
use diesel::prelude::*;
use diesel::SelectableHelper;
use diesel_async::{
    pooled_connection::AsyncDieselConnectionManager, AsyncPgConnection, RunQueryDsl,
};
use diesel_migrations::{embed_migrations, EmbeddedMigrations, MigrationHarness};
use serde::{Deserialize, Serialize};
use std::net::SocketAddr;

//Embed migrations to run them on startup
pub const MIGRATIONS: EmbeddedMigrations = embed_migrations!();

//Define the table schema (normally generated by diesel print-schema)
diesel::table! {
    users(id){
        id -> Integer,
        name -> Text,
        email -> Text,
        created_date -> Timestamptz
    }
}

// ---Models ---
#[derive(Debug, Serialize, Deserialize, Queryable, Selectable)]
#[diesel(table_name=users)]
#[diesel(check_for_backend(Pg))]
pub struct User {
    pub id: i32,
    pub name: String,
    pub email: String,
    pub created_date: NaiveDateTime,
}

#[derive(Debug, Deserialize, Insertable)]
#[diesel(table_name = users)]
pub struct NewUser {
    pub name: String,
    pub email: String,
}

#[derive(Debug, Deserialize, AsChangeset)]
#[diesel(table_name = users)]
pub struct UpdateUser {
    pub name: Option<String>,
    pub email: Option<String>,
}

//Type alias for the connection pool
type Pool = bb8::Pool<AsyncDieselConnectionManager<AsyncPgConnection>>;

#[tokio::main]
async fn main() {
    dotenv::dotenv().ok();
    let database_url = std::env::var("DATABASE_URL").expect("DATABASE_URL must be set");

    //Run migrations SYNCHRONOUSLY before setting up the async pool
    run_migrations(&database_url);

    //Setup Connection Pool
    let config: AsyncDieselConnectionManager<AsyncPgConnection> =
        AsyncDieselConnectionManager::<AsyncPgConnection>::new(database_url);
    let pool: bb8::Pool<AsyncDieselConnectionManager<AsyncPgConnection>> = bb8::Pool::builder()
        .build(config)
        .await
        .expect("Failed to create pool");

    //Build the application with a single route
    let app = Router::new()
        .route("/", get(|| async { "Hello, World" }))
        .route("/users", get(list_users).post(create_user))
        .route(
            "/users/{id}",
            get(get_user).patch(update_user).delete(delete_user),
        )
        .with_state(pool);

    //Define the address (localhost:5000)
    let address = SocketAddr::from(([127, 0, 0, 1], 5000));

    println!("Server is up and running on http://{}", address);

    //Start the server
    let listener = tokio::net::TcpListener::bind(address).await.unwrap();
    axum::serve(listener, app).await.unwrap();
}

fn run_migrations(database_url: &str) {
    let mut connection = PgConnection::establish(database_url)
        .expect("Failed to connect to database for migrations");

    connection
        .run_pending_migrations(MIGRATIONS)
        .expect("Failed to run migrations");

    println!("Migrations completed successfully");
}

// ---CRUD Handlers---

//CREATE
async fn create_user(
    State(pool): State<Pool>,
    Json(new_user): Json<NewUser>,
) -> Result<Json<User>, (StatusCode, String)> {
    let mut conn = pool.get().await.map_err(internal_error)?;

    let user = diesel::insert_into(users::table)
        .values(&new_user)
        .returning(User::as_returning())
        .get_result(&mut conn)
        .await
        .map_err(internal_error)?;
    Ok(Json(user))
}

//READ (ALL)
async fn list_users(State(pool): State<Pool>) -> Result<Json<Vec<User>>, (StatusCode, String)> {
    let mut conn = pool.get().await.map_err(internal_error)?;

    let users = users::table
        .select(User::as_select())
        .load(&mut conn)
        .await
        .map_err(internal_error)?;

    Ok(Json(users))
}

// READ(One)
async fn get_user(
    State(pool): State<Pool>,
    Path(user_id): Path<i32>,
) -> Result<Json<User>, (StatusCode, String)> {
    let mut conn = pool.get().await.map_err(internal_error)?;

    let user = users::table
        .find(user_id)
        .select(User::as_select())
        .first(&mut conn)
        .await
        .map_err(|e| match e {
            diesel::result::Error::NotFound => {
                (StatusCode::NOT_FOUND, "User not found".to_string())
            }
            _ => internal_error(e),
        })?;

    Ok(Json(user))
}

//UPDATE
async fn update_user(
    State(pool): State<Pool>,
    Path(user_id): Path<i32>,
    Json(update_data): Json<UpdateUser>,
) -> Result<Json<User>, (StatusCode, String)> {
    let mut conn = pool.get().await.map_err(internal_error)?;

    let user = diesel::update(users::table.find(user_id))
        .set(&update_data)
        .returning(User::as_returning())
        .get_result(&mut conn)
        .await
        .map_err(|e| match e {
            diesel::result::Error::NotFound => {
                (StatusCode::NOT_FOUND, "User not found".to_string())
            }
            _ => internal_error(e),
        })?;

    Ok(Json(user))
}

//DELETE
async fn delete_user(
    State(pool): State<Pool>,
    Path(user_id): Path<i32>,
) -> Result<StatusCode, (StatusCode, String)> {
    let mut conn = pool.get().await.map_err(internal_error)?;

    let row_deleted = diesel::delete(users::table.find(user_id))
        .execute(&mut conn)
        .await
        .map_err(internal_error)?;

    if row_deleted == 0 {
        Err((StatusCode::NOT_FOUND, "User not found".to_string()))
    } else {
        Ok(StatusCode::NO_CONTENT)
    }
}

fn internal_error<E>(err: E) -> (StatusCode, String)
where
    E: std::error::Error,
{
    (StatusCode::INTERNAL_SERVER_ERROR, err.to_string())
}
